language: node_js

notifications:
  email: false

node_js:
  - "8"

env:
  - DISPLAY=:99.0

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
  - npm run test

branches:
  only:
    - master
